## Lesson 01 — Python, IPython, Packages, and Jupyter Notebooks



In the first lesson, we overview the syllabus and schedule for the course.

To get a preview of data science using Python, check out the video 
[10-minute Tour of Pandas by Wes McKinney](https://www.youtube.com/watch?v=_T8LGqJtuGc), the creator
of Pandas.

### Readings

* [What is Python? Executive summary](https://www.python.org/doc/essays/blurb/)
* [Python Language Basics, IPython, and Jupyter Notebooks (McKinney)](https://wesmckinney.com/book/python-basics)
* [The Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/latest/notebook.html)
* [10-minute Tour of Pandas by Wes McKinney](https://www.youtube.com/watch?v=_T8LGqJtuGc)

### Table of Contents

* [Installation](#Installing-Python)
* [IPython and Jupyter](#IPython-and-Jupyter)
* [Downloading Today's Lesson](#Downloading-Today's-Lesson)
* [Python Syntax](#Syntax)
* [Data Types](#Data-types)
* [Control Structures](#Loops-and-Control-Structures)
* [Version](#Determining-Your-Python-Version)

### Installing Python

Installing Python is straight forward, and the best installation will depend on your operating system:

#### Windows

- Go the downloads page at [Python.org](https://www.python.org/downloads/)
- Click the download button: it should auto suggest you the latest version already.
- Make sure you select the options **Add python.exe to path** and include all optional installations.
- If you need a more detailed installation tutorial with images, follow [this tutorial from DigitalOcean.](https://www.digitalocean.com/community/tutorials/install-python-windows-10)

![install-python](../images/install-python.png)

#### MacOs

- Python can be installed with [brew](https://brew.sh/), using `brew install python`
- Brew is the recommended way to install it, since it will handle the future security updates of your installation.

#### Linux

- Most distribution will have Python installed, which is bundled with the system. To check which Python you have installed, simply type `python --version` in a terminal window.
- You might need to install extras, like pip. On Ubuntu, you can do that by running `sudo apt-get install python3-pip`

### IPython and Jupyter

IPython offers enhanced interactive Python shells with support for data visualization, distributed and parallel computation, and the browser-based Jupyter notebook. Jupyter notebook provides support for code, text, mathematical expressions, inline plots, and other rich media.

#### Python command-line interpreter

To open the Python interpreter, go to your terminal and type:

```
python
```

#### IPython command-line interpreter

To open the IPython interpreter, go to your terminal and type:

```
ipython
```

#### Jupyter (IPython) notebooks

To launch a Jupyter notebook, open Terminal and type:

```
source venv/bin/activate
jupyter notebook
```

Your notebook now can be acessed using your browser under http://localhost:8888

Open up a new notebook, then check out **Help > Show Keyboard Shortcuts...**.

The most important shortcuts are:

- **Shift + Enter**: Run the current line and skip to the next.
- **Arrows**: Will go up and down on the cells
- **Alt + Enter**: Will add a cell under your current cell.
- **Esc**: When editing the cell, will leave edit mode.
- **Enter**: When viewing the cell, will enter edit mode.
- **d d**: When viewing the cell, will delete it.

### Downloading Today's Lesson

At the start of every class, we will follow a regular routine of navigating to our lessons folder, downloading the day's lesson, activating our Python environment, and launching Jupyter notebook.

For all users:

1. Open Terminal (macOS and Linux users) or Git Bash (Windows users)
2. Clone the repository with `git clone https://github.com/bvanelli/python-for-data-analysis.git`
3. Navigate to the cloned repository with `cd python-for-data-analysis`
4. Create a virtual environment with `python3 -m venv venv`
5. Activate the virtual environment with `source venv/bin/activate`
6. If you are on windows, the command is `source venv/Scripts/activate`
7. Install the required packages with `pip install -r requirements.txt`
8. Launch the notebook with `jupyter notebook`

Your notebook will now show:

![juypter-running](../images/jupyter-running.png)

<a id="syntax"></a>

## Python Crash Course

In this tutorial we will cover some basic aspects of Python using IPython (Jupyter) notebooks. 

1. Syntax
2. Data types
3. Loops and control structures
4. numpy, scipy, math

### Syntax

In [1]:
2 + 2

4

In [2]:
x = 5
y = 2
x * y

10

In [3]:
x**y

25

In [4]:
print("Hello, world!")

Hello, world!


In [74]:
print(f"{x} raised to power of {y} equals {x ** y}")

4 raised to power of 2 equals 16


### Data Types

#### Booleans

'True' and 'False' have special meaning in Python.

In [6]:
a = True
b = False

In [7]:
a == True

True

In [8]:
b == True

False

In [9]:
a or b

True

In [10]:
a and b

False

#### Numbers: integers and floats

Numbers are pretty straightforward, especially in Python 3.

In [11]:
1 + 2

3

In [12]:
1.0 + 2.0

3.0

In [13]:
1 / 2

0.5

In [14]:
1.0 / 2.0

0.5

In [15]:
type(1)

int

In [16]:
type(1 / 2)

float

#### Strings

The next four data types -- strings, lists, tuples, arrays -- are all sequences.

Strings are sequences of characters.

In [17]:
s = "Hello, world"

In [18]:
type(s)

str

In [19]:
s[0:4]

'Hell'

In [20]:
s + "!"

'Hello, world!'

In [21]:
s

'Hello, world'

In [22]:
s = s + "!"

In [23]:
s

'Hello, world!'

#### Lists

Lists are _mutable_ sequences of anything.

In [24]:
l = [0, 1, 1, 2, 3, 5, 8]

In [25]:
m = [5, 2, "a", "xxx", True, [0, 1]]

In [26]:
l[0:3]

[0, 1, 1]

In [27]:
m[4]

True

In [28]:
m[4] = False

In [29]:
m[4:]

[False, [0, 1]]

#### Tuples

Tuples are immutable sequences of anything (similar to lists except you can't change them).

In [30]:
n = (3, 5, 6)

In [31]:
n[0]

3

In [32]:
n[0] = 2

TypeError: 'tuple' object does not support item assignment

#### Arrays (numpy)
You will first need to install the numpy module for usage

In [72]:
%pip install numpy

  Using cached numpy-2.3.2-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Using cached numpy-2.3.2-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)
Note: you may need to restart the kernel to use updated packages.


In [34]:
# Import modules to use
import math
import numpy as np

In [35]:
mylist = [0, 2, 4]
np.array(mylist)

array([0, 2, 4])

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [38]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [39]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [40]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [41]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
np.random.rand()

0.420433919322334

In [43]:
np.random.rand(5)

array([0.01370907, 0.24161808, 0.48960709, 0.91225466, 0.07140464])

#### Sets

Sets are unordered collections of unique objects.

In [44]:
s1 = {"a", "b", "c"}
s2 = {"a", "d", "e"}

In [45]:
s1 & s2

{'a'}

In [46]:
s1 | s2

{'a', 'b', 'c', 'd', 'e'}

In [47]:
s3 = set(l)
s4 = set(m[0:2])

In [48]:
s3 & s4

{2, 5}

In [49]:
s3 | s4

{0, 1, 2, 3, 5, 8}

In [50]:
s3 - s4

{0, 1, 3, 8}

#### Dictionaries

Dictionaries or 'dicts' are hash tables, where a key points to a value.

In [51]:
d = {"name": "John Doe", "age": 27, "dob": "7/20/1989"}

In [52]:
d

{'name': 'John Doe', 'age': 27, 'dob': '7/20/1989'}

In [53]:
d["name"]

'John Doe'

In [54]:
d["zip"] = 92039

### Loops and Control Structures

#### Boolean and comparison operations

In [55]:
x = 5
(x < 6) and (x > 4)

True

In [56]:
x != 4

True

In [57]:
5 in [3, 4, 5]

True

In [58]:
"ell" in "Hello"

True

In [59]:
len("Hello") >= 5

True

#### if tests

In [60]:
if "d" in "abc":
    print("Learn your alphabet.")
elif 2 + 2 == 5:
    print("Sometimes yes.")
else:
    print("Nothing is true.")

Nothing is true.


#### while loops

In [61]:
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


In [62]:
i

5

#### for loops

In [63]:
for x in [0, 1, 2, 3, 4]:
    print(x**2)

0
1
4
9
16


### Determining Your Python Version

#### Method 1: sys

In [64]:
import sys

In [65]:
sys.version

'3.13.7 (main, Aug 14 2025, 11:12:11) [Clang 17.0.0 (clang-1700.0.13.3)]'

#### Method 2: platform

In [66]:
import platform

In [67]:
platform.python_version()

'3.13.7'

In [68]:
platform.version()

'Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:29 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6000'

#### Method 3: version_information

In [70]:
%pip install version_information

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for version_information: filename=version_information-1.0.4-py3-none-any.whl size=3934 sha256=49dba89c916054b936cd3b19983ffe6095e14f250706db0d4e88e90932b79526
  Stored in directory: /Users/brunno.vanelli/Library/Caches/pip/wheels/d7/71/4c/6b870f444d85efe32d273ea720a595cffb8c6d61fddee77569
Successfully built version_information
Note: you may need to restart the kernel to use updated packages.


In [71]:
# first install: pip install version_information
%reload_ext version_information
%version_information math, numpy, sys, platform

/Users/brunno.vanelli/Documents/git/python-for-data-analysis/venv/lib/python3.13/site-packages/version_information/version_information.py:60: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


Software versions
Python 3.13.7 64bit [Clang 17.0.0 (clang-1700.0.13.3)]
IPython 9.5.0
OS macOS 15.6.1 arm64 arm 64bit Mach O
math The 'math' distribution was not found and is required by the application
numpy 2.3.2
sys The 'sys' distribution was not found and is required by the application
platform 1.0.8
Fri Sep 05 22:28:59 2025 CEST