## Lesson 01 — Python, IPython, Packages, and Jupyter Notebooks



In the first lesson, we overview the syllabus and schedule for the course.

To get a preview of data science using Python, check out the video 
[10-minute Tour of Pandas by Wes McKinney](https://www.youtube.com/watch?v=_T8LGqJtuGc), the creator
of Pandas.

In this tutorial we will cover some basic aspects of Python using IPython (Jupyter) notebooks. We will launch our first notebook, as well as giving some introduction about the following topics: 

* Syntax
* Data types
* Loops and control structures
* numpy, math

### Readings

* [_What is Python? Executive summary_, by Python](https://www.python.org/doc/essays/blurb/)
* [_Python Language Basics, IPython, and Jupyter Notebooks_, by Wes McKinney](https://wesmckinney.com/book/python-basics)
* [_The Jupyter Notebook_, by Jupyter](https://jupyter-notebook.readthedocs.io/en/latest/notebook.html)
* [_Python in 100 Seconds_ (video), by Fireship](https://www.youtube.com/watch?v=x7X9w_GIm1s)
* [_10-minute Tour of Pandas_ (video), by Wes McKinney](https://www.youtube.com/watch?v=_T8LGqJtuGc)

### Table of Contents

* [Installation](#Installing-Python)
* [IPython and Jupyter](#IPython-and-Jupyter)
* [Downloading Today's Lesson](#Downloading-Today's-Lesson)
* [Syntax](#Syntax)
* [Data Types](#Data-Types)
* [Loops and Control Structures](#Loops-and-Control-Structures)
* [Determining Your Python Version](#Determining-Your-Python-Version)

### Installing Python

Installing Python is straight forward, and the best installation will depend on your operating system:

#### Windows

- Go the downloads page at [Python.org](https://www.python.org/downloads/)
- Click the download button: it should auto suggest you the latest version already.
- Make sure you select the options **Add python.exe to path** and include all optional installations.
- If you need a more detailed installation tutorial with images, follow [this tutorial from DigitalOcean.](https://www.digitalocean.com/community/tutorials/install-python-windows-10)

<center><img src="../images/install-python.png" width="60%"/></center>

#### macOS

- Python can be installed with [brew](https://brew.sh/), using `brew install python`
- Brew is the **recommended way** to install it, since it will handle the future security updates of your installation.

#### Linux

- Most distribution will have Python installed, which is bundled with the system. To check which Python you have installed, simply type `python --version` in a terminal window.
- You might need to install extras, like pip. On Ubuntu, you can do that by running `sudo apt-get install python3-pip`

### Command prompt

When running Python applications, we often refer to the term _Command line_ or _Terminal_. They are the direct interface to your Python interpreter.

On **Windows**, you are looking for an application called _Command Prompt_ or _Powershell_:

<center><img src="../images/command-prompt.png" width="60%"/></center>

On **macOS** and on **Linux**, the app is called _Terminal_.

### IPython and Jupyter

IPython offers enhanced interactive Python shells with support for data visualization, distributed and parallel computation, and the browser-based Jupyter notebook. Jupyter notebook provides support for code, text, mathematical expressions, inline plots, and other rich media.

#### Python command-line interpreter

To open the Python interpreter, go to your terminal and type:

```
python
```

Here is how it should look like on Windows:

<center><img src="../images/windows-cmd.png" width="60%"/></center>

In some systems, `python` might be aliased as `python3` instead. For all purposes, **you can consider those commands the same thing**.

#### IPython command-line interpreter

To open the IPython interpreter, go to your terminal and type:

```
ipython
```

#### Jupyter (IPython) notebooks

To launch a Jupyter notebook, we usually create a virtual environment to install the package:

```bash
python -m venv venv
```

Then activate your new environment (needs to be done every time you start a new terminal):

```bash
source venv/bin/activate
```

If you are on **Windows**, the command will be slighly different:

```bash
.\venv\Scripts\activate
```

When launching the application for the first time, you also need to install the packages with `pip`:

```bash
pip install -r requirements.txt
```

Now, you can open the Terminal and type:

```bash
jupyter notebook
```

Your notebook now can be acessed using your browser under http://localhost:8888

Open up a new notebook, then check out **Help > Show Keyboard Shortcuts...**.

The most important shortcuts are:

- **Shift + Enter**: Run the current line and skip to the next.
- **Arrows**: Will go up and down on the cells
- **Alt + Enter**: Will add a cell under your current cell.
- **Esc**: When editing the cell, will leave edit mode.
- **Enter**: When viewing the cell, will enter edit mode.
- **d d**: When viewing the cell, will delete it.

### Downloading Today's Lesson

At the start of every class, we will follow a regular routine of navigating to our lessons folder, downloading the day's lesson, activating our Python environment, and launching Jupyter notebook.

To follow the steps to set up the project, make sure you have also [installed git](https://git-scm.com/install/).

For all users:

1. Open Terminal (macOS and Linux users) or Git Bash (Windows users)
2. Clone the repository with `git clone https://github.com/bvanelli/python-for-data-analysis.git`
3. Navigate to the cloned repository with `cd python-for-data-analysis`
4. Create a virtual environment with `python -m venv venv`
5. Activate the virtual environment with `source venv/bin/activate`. If you are on **Windows**, the command is `.\venv\Scripts\activate`
6. Install the required packages with `pip install -r requirements.txt`
7. Launch the notebook with `jupyter notebook`

Your notebook will now show under http://localhost:8888:

![Running a Jupyter Notebook](../images/jupyter-running.png)

### Syntax

Using the basic syntax, you can use Python essential as a calculator:

In [1]:
2 + 2

4

In [2]:
2 * 3

6

Python variables don't have to be typed, so you can directly assign values using the `=` sign, and do indirect operations:

In [3]:
x = 5
y = 2
x * y

10

The goal being reusing the values for future operations:

In [4]:
x**y

25

For interaction with the user (and output outside Jupyter Notebooks) you use the `print` statement: 

In [5]:
print("Hello, world!")

Hello, world!


Use an `f-string` to output variables within the text:

In [6]:
#     ∨ Notice the `f` character          ∨∨∨∨∨∨∨∨ You can evaluate entire expressions
print(f"{x} raised to power of {y} equals {x ** y}")

5 raised to power of 2 equals 25


### Data Types

#### Booleans

'True' and 'False' have special meaning in Python. You can use them in comparisons and boolean operations.

In [7]:
a = True
b = False

Compare equality for booleans with the `is` statement (avoid using `a == True`):

In [8]:
a is True

True

In [9]:
b is True

False

In [10]:
a or b

True

In [11]:
a and b

False

And here is one example why you should avoid using the `=` operator for booleans, since `bool` is a subclass of `int`:

In [12]:
a == 1

True

#### Numbers: integers and floats

Numbers are also pretty straightforward. You can use `+` to sum, `*` to multiple, `/` to divide, `**` as exponentiation.

If you add a dot `.` to the number, it will be read as a float and contain decimal cases. The datatype from the output will be inferred from the operation.

In [13]:
1 + 2

3

In [14]:
1.0 + 2.0

3.0

In [15]:
1 / 2

0.5

In [16]:
1.0 / 2.0

0.5

The [`type` function](https://docs.python.org/3/library/functions.html#type) is useful to infer the type of any object:

In [17]:
type(1)

int

In [18]:
type(1 / 2)

float

#### Strings

The next four data types -- strings, lists, tuples, arrays -- are all sequences.

Strings are sequences of characters.

In [19]:
s = "Hello, world"

In [20]:
type(s)

str

You can sub-select sequences using the range operation:

In [21]:
s[0:4]

'Hell'

And extend them using the `+` operator:

In [22]:
s + " 👋"

'Hello, world 👋'

In [23]:
s

'Hello, world'

In [24]:
s = s + " 👋"

In [25]:
s

'Hello, world 👋'

#### Lists

Lists are _mutable_ sequences of anything. You can initialize one using the square brackets `[]`:

In [26]:
l = [0, 1, 1, 2, 3, 5, 8]

You can mix multiple datatypes inside the same list, **although not recommended**:

In [27]:
m = [5, 2, "a", "xxx", True, [0, 1]]

In [28]:
l[0:3]

[0, 1, 1]

In [29]:
m[4]

True

In [30]:
m[4] = False

In [31]:
m[4:]

[False, [0, 1]]

#### Tuples

Tuples are immutable sequences of anything (similar to lists except you can't change them).

In [32]:
n = (3, 5, 6)

In [33]:
n[0]

3

Since a tuple cannot be modified, the following line will fail if you execute it. Try it out! Modify the following raw cell to a code cell and run it.

#### Sets

Sets are unordered collections of unique objects.

In [34]:
s1 = {"a", "b", "c"}
s2 = {"a", "d", "e"}

In [35]:
s1 & s2

{'a'}

In [36]:
s1 | s2

{'a', 'b', 'c', 'd', 'e'}

In [37]:
s3 = set(l)
s4 = set(m[0:2])

In [38]:
s3 & s4

{2, 5}

In [39]:
s3 | s4

{0, 1, 2, 3, 5, 8}

In [40]:
s3 - s4

{0, 1, 3, 8}

#### Dictionaries

Dictionaries or 'dicts' are hash tables, where a key points to a value.

In [41]:
d = {"name": "John Doe", "age": 27, "dob": "7/20/1989"}

In [42]:
d

{'name': 'John Doe', 'age': 27, 'dob': '7/20/1989'}

In [43]:
d["name"]

'John Doe'

In [44]:
d["zip"] = 92039

#### Arrays (numpy)

Python arrays are very useful, but they lack support for many for data science specific functionality, such as quickly evaluating statistics, using it as a matrix, etc. We often use [numpy](https://numpy.org/) as a replacement for it.

You will first need to install the numpy module for usage:

In [45]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


We then import the module with an `import` statement:

In [46]:
# Import modules to use
import math
import numpy as np

You can convert a Python list directly into a numpy array (will preserve datatypes):

In [47]:
mylist = [0, 2, 4]
arr = np.array(mylist)
arr

array([0, 2, 4])

Or initialize an array with zeroes:

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Some functions help you generate you ranges of numbers:

In [49]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [50]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [51]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [52]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [53]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [54]:
np.random.rand()

0.2703903252051847

In [55]:
np.random.rand(5)

array([0.75890446, 0.5121273 , 0.55423336, 0.23270754, 0.27263962])

The advantage is of course doing mathematical operations directly on those arrays:

In [56]:
arr

array([0, 2, 4])

In [57]:
arr.sum()

np.int64(6)

In [58]:
arr.min()

np.int64(0)

In [59]:
arr.max()

np.int64(4)

### Loops and Control Structures

Control structures let you **make decisions** and **repeat tasks**. You use boolean expressions with `if`-statements for making decisions, and `for` and `while` loops for repetition.

#### Boolean and comparison operations

You can compare with the basic comparison operators `==`, `<`, `>`, `<=`, `>=`, `in`. You can join statements together using the `and` and `or` statements.

In [60]:
x = 5
(x < 6) and (x > 4)

True

In [61]:
x != 4

True

In [62]:
x in [3, 4, 5]

True

In [63]:
"ell" in "Hello"

True

In [64]:
len("Hello") >= x

True

#### if tests

Once you have a boolean expression, you can use it in an `if`-statement to make decisions.

In [65]:
if "d" in "abc":
    print("Learn your alphabet.")
elif 2 + 2 == 5:
    print("Maybe not.")
else:
    print("Nothing is true.")

Nothing is true.


Note that you can directly use boolean statements in the `if`-statement:

In [66]:
var = True
if var:
    print("Variable is True")

Variable is True


#### while loops

You can iterate until a condition is true by using the `while` loops.

Note that, **if the condition is never met, the loop will block forever**. This is why `for` loops are preferred.

In [67]:
x = 0
while x < 5:
    print(x**2)
    x += 1

0
1
4
9
16


In [68]:
x

5

#### for loops

`for` loops are most of the time a better alternative to `while` loops, as they are always guaranteed to finish (as long as your iterable is finite). They also allow for a more concise code and can operate on iterables:

In [69]:
for x in [0, 1, 2, 3, 4]:
    print(x**2)

0
1
4
9
16


Often you will see the term *Pythonic*, which refers to writing readable, idiomatic Python code. The same code could be written in a more idiomatic way by using the `range` built-in function:

In [70]:
for x in range(5):
    print(x**2)

0
1
4
9
16


### Determining Your Python Version

New Python versions introduce new features, improve performance, and fix bugs and security vulnerabilities. It is recommended that you follow the release cycle and migrate your application to benefit from those improvements.

You can check your current Python version in many ways.

#### Method 1: sys

In [71]:
import sys

In [72]:
sys.version

'3.14.3 (main, Feb  3 2026, 15:32:20) [Clang 17.0.0 (clang-1700.6.3.2)]'

#### Method 2: platform

In [73]:
import platform

In [74]:
platform.python_version()

'3.14.3'

In [75]:
platform.version()

'Darwin Kernel Version 25.3.0: Wed Jan 28 20:54:46 PST 2026; root:xnu-12377.91.3~2/RELEASE_ARM64_T6000'

#### Method 3: version_information

In [76]:
%pip install version_information

Note: you may need to restart the kernel to use updated packages.


In [77]:
# first install: pip install version_information
%reload_ext version_information
%version_information math, numpy, sys, platform

Software versions
Python 3.14.3 64bit [Clang 17.0.0 (clang-1700.6.3.2)]
IPython 9.11.0
OS macOS 26.3.1 arm64 arm 64bit Mach O
math module 'math' has no attribute '__version__'
numpy 2.4.3
sys module 'sys' has no attribute '__version__'
platform 1.0.9
Mon Mar 16 11:22:19 2026 -03

#### Method 4: Command line

You can verify which Python version you are running via the command line by invoking the Python command:

```bash
>>> python --version
Python 3.14.3
```